Repository pgmoneta/pgmoneta, pull requests merged in 2024-03, with the labels that each got.

#199 [#187] Parse .history and expose to prometheus
  src/include/pgmoneta.h
  src/include/wal.h
  src/libpgmoneta/bzip2_compression.c
  src/libpgmoneta/configuration.c
  src/libpgmoneta/gzip_compression.c
  src/libpgmoneta/lz4_compression.c
  src/libpgmoneta/prometheus.c
  src/libpgmoneta/wal.c
  src/libpgmoneta/zstandard_compression.c
Labels: feature

#203 [#187]copy cur_timeline & initialize timeline_history
  src/libpgmoneta/configuration.c
  src/libpgmoneta/wal.c
Labels: enhancement

#201 [#200] Expose current streaming WAL filename to Prometheus interface
  AUTHORS
  src/include/pgmoneta.h
  src/libpgmoneta/configuration.c
  src/libpgmoneta/prometheus.c
  src/libpgmoneta/wal.c
Labels: feature

#208 [#207] Expose WAL log sequence number (pgmoneta_current_wal_lsn) to Prometheus
  AUTHORS
  src/include/pgmoneta.h
  src/libpgmoneta/configuration.c
  src/libpgmoneta/prometheus.c
  src/libpgmoneta/wal.c
Labels: feature

#214 [#218] Expose backup throughput to prometheus
  src/libpgmoneta/prometheus.c
Labels: feature

#210 [#219] Install pgmoneta
  doc/DEVELOPERS.md
  doc/PR_GUIDE.md
  pgmoneta.spec
Labels: documentation

#217 [#216] Implement a mechanism to exclude some files in the first restore round
  src/include/restore.h
  src/include/utils.h
  src/include/workflow.h
  src/libpgmoneta/restore.c
  src/libpgmoneta/utils.c
  src/libpgmoneta/wf_restore.c
  src/libpgmoneta/workflow.c
Labels: feature

#223 [#221] Add a label of minor version in backup.info
  AUTHORS
  src/include/info.h
  src/include/pgmoneta.h
  src/libpgmoneta/server.c
  src/libpgmoneta/wf_backup.c
Labels: feature

#224 [#205] Add json format option for command output
  src/cli.c
  src/include/json.h
  src/include/management.h
  src/libpgmoneta/json.c
  src/libpgmoneta/management.c
Labels: feature

#226 [#225]Fix is-alive command
  src/libpgmoneta/management.c
Labels: bug

#234 Update DEVELOPERS.md Issue#233
  doc/DEVELOPERS.md
Labels: documentation

#229 [#205] Porting command line parsing infrastructure
  contrib/shell_comp/pgmoneta_comp.bash
  contrib/shell_comp/pgmoneta_comp.zsh
  doc/ARCHITECTURE.md
  doc/CLI.md
  doc/DEVELOPERS.md
  doc/GETTING_STARTED.md
  doc/man/pgmoneta-admin.1.rst
  doc/man/pgmoneta-cli.1.rst
  doc/tutorial/01_install.md
  doc/tutorial/03_remote_management.md
  src/CMakeLists.txt
  src/admin.c
  src/cli.c
  src/include/pgmoneta.h
  src/include/utils.h
  src/libpgmoneta/utils.c
Labels: feature
