Repository pgmoneta/pgmoneta, pull requests merged in 2024-04, with the labels that each got.

#242 [#241] Add CMake rules to find and link libpthread
  CMakeLists.txt
  cmake/FindTHREAD.cmake
  src/CMakeLists.txt
  src/libpgmoneta/utils.c
Labels: bug

#227 [#197] Rate limit: Disk
  .gitignore
  doc/CONFIGURATION.md
  src/include/message.h
  src/include/pgmoneta.h
  src/include/utils.h
  src/libpgmoneta/configuration.c
  src/libpgmoneta/message.c
  src/libpgmoneta/utils.c
  src/libpgmoneta/wf_backup.c
Labels: feature

#244 [#239] Add warning for illegal key while setting master-key manually
  src/admin.c
Labels: feature

#240 Prometheus metric for backup version shows major and minor version
  AUTHORS
  src/libpgmoneta/info.c
  src/libpgmoneta/prometheus.c
Labels: feature

#251 [#250] Broken For loop
  src/main.c
Labels: bug

#252 [#187] Receive WAL end pos of backup from server
  src/include/info.h
  src/include/utils.h
  src/libpgmoneta/info.c
  src/libpgmoneta/prometheus.c
  src/libpgmoneta/utils.c
  src/libpgmoneta/wf_backup.c
Labels: feature

#258 memcpy count should not be larger than dst/src len
  src/libpgmoneta/wf_backup.c
Labels: bug

#261 [#196] Network rate limit for backup
  doc/CONFIGURATION.md
  src/include/message.h
  src/include/network.h
  src/include/pgmoneta.h
  src/libpgmoneta/configuration.c
  src/libpgmoneta/message.c
  src/libpgmoneta/network.c
  src/libpgmoneta/wal.c
  src/libpgmoneta/wf_backup.c
Labels: feature

#271 [#270] Add CI backup/restore workflow
  .github/workflows/ci.yml
Labels: enhancement

#272 [#256] Documentations for mandatory wal slot
  doc/CONFIGURATION.md
  doc/DEVELOPERS.md
  doc/GETTING_STARTED.md
  doc/tutorial/01_install.md
  doc/tutorial/02_replication_slot.md
Labels: documentation

#238 Adding PGMONETA_VERSION in backup.info Issue #235
  AUTHORS
  src/libpgmoneta/info.c
  src/libpgmoneta/prometheus.c
Labels: feature
