Repository pgmoneta/pgmoneta, pull requests merged in 2025-10, with the labels that each got.

#761 [#670] Implemented filtering on xid
  doc/CONFIGURATION.md
  doc/DEVELOPERS.md
  doc/WALFILTER.md
  doc/man/pgmoneta-walfilter.1.rst
  doc/manual/en/17-wal-tools.md
  src/include/yaml_utils.h
  src/libpgmoneta/walfile/wal_reader.c
  src/libpgmoneta/yaml_utils.c
  src/walfilter.c
Labels: feature

#778 [#777] Fix RPM Build Issues: Missing Test Directory, Man Pages, Binaries, and RST Formatting Errors
  CMakeLists.txt
  doc/CMakeLists.txt
  doc/RPM.md
  doc/man/pgmoneta-walinfo.1.rst
  pgmoneta.spec
Labels: bug

#773 [#772] Extend API to return current timeline ID
  doc/manual/en/80-server-api.md
  src/include/server.h
  src/libpgmoneta/server.c
  test/testcases/test_server_api.c
  test/testcases/test_wal_summary.c
Labels: enhancement
