Repository pgmoneta/pgmoneta, pull requests merged in 2025-09, with the labels that each got.

#747 [#746] Memory Leak while converting bytea to binary for a chunk not present
  src/libpgmoneta/server.c
Labels: bug

#750 [#745] Generate prometheus manual
  contrib/prometheus_scrape/README.md
  contrib/prometheus_scrape/extra.info
  contrib/prometheus_scrape/prometheus.py
  doc/manual/en/10-prometheus.md
Labels: documentation

#674 pgmoneta-walfilter: DELETE
  .github/workflows/ci.yml
  CMakeLists.txt
  cmake/FindLibYAML.cmake
  doc/CMakeLists.txt
  doc/CONFIGURATION.md
  doc/DEVELOPERS.md
  doc/WAL.md
  doc/WALFILTER.md
  doc/etc/pgmoneta_walfilter.conf
  doc/man/pgmoneta-walfilter.1.rst
  doc/manual/en/17-wal-tools.md
  doc/manual/en/78-wal.md
  src/CMakeLists.txt
  src/include/configuration.h
  src/include/logging.h
  src/include/pgmoneta.h
  src/include/utils.h
  src/include/walfile/rmgr.h
  src/include/walfile/wal_reader.h
  src/include/yaml_utils.h
  src/libpgmoneta/configuration.c
  src/libpgmoneta/logging.c
  src/libpgmoneta/security.c
  src/libpgmoneta/server.c
  src/libpgmoneta/utils.c
  src/libpgmoneta/walfile.c
  src/libpgmoneta/walfile/wal_reader.c
  src/libpgmoneta/yaml_utils.c
  src/walfilter.c
Labels: feature

#756 [#755] Refactor WAL Summarizer
  src/include/walfile/wal_summary.h
  src/libpgmoneta/walfile/wal_summary.c
  test/testcases/test_wal_summary.c
Labels: enhancement

#760 [#758] Fetch metadata of a file from the postgres server
  doc/manual/en/80-server-api.md
  src/include/server.h
  src/libpgmoneta/server.c
  test/include/tssuite.h
  test/postgresql/src/postgresql17/conf/setup.sql
  test/runner.c
  test/testcases/test_server_api.c
Labels: feature
