Repository pgmoneta/pgmoneta, pull requests merged in 2025-01, with the labels that each got.

#447 [#446] Fix lz4 decompress logic
  src/libpgmoneta/lz4_compression.c
Labels: bug

#450 Allow to use CRC32C hardware implementation on arm64
  AUTHORS
  CMakeLists.txt
  doc/manual/97-acknowledgement.md
  doc/manual/advanced/97-acknowledgement.md
  src/libpgmoneta/security.c
Labels: enhancement

#449 [#436] Allow file based commands to run without a server
  src/cli.c
Labels: enhancement

#459 [#434] Get the segment size as an optional argument
  src/libpgmoneta/walfile/wal_reader.c
Labels: feature

#462 [#460] Proper error checking in master_key()
  src/admin.c
Labels: bug
