Repository pgmoneta/pgmoneta, pull requests merged in 2025-05, with the labels that each got.

#624 [#623] test suite: Development servers
  test/testsuite.sh
Labels: bug

#618 [#414] Reading Wal files from a directory
  doc/manual/dev-08-wal.md
  src/include/utils.h
  src/include/walfile.h
  src/include/walfile/wal_reader.h
  src/libpgmoneta/utils.c
  src/libpgmoneta/walfile.c
  src/libpgmoneta/walfile/wal_reader.c
  src/walinfo.c
Labels: feature

#639 [#637] Hindi: Verification and Docker
  doc/manual/advanced/hi/04-configuration.md
  doc/manual/advanced/hi/05-backup.md
  doc/manual/advanced/hi/12-docker.md
Labels: documentation

#641 [#640]Fix Hash validation
  src/libpgmoneta/verify.c
Labels: bug

#642 [#547]Support Multiple Hot Standby Directories
  doc/CONFIGURATION.md
  doc/tutorial/13_hot_standby.md
  src/include/pgmoneta.h
  src/include/utils.h
  src/libpgmoneta/configuration.c
  src/libpgmoneta/prometheus.c
  src/libpgmoneta/status.c
  src/libpgmoneta/utils.c
  src/libpgmoneta/wf_delete.c
  src/libpgmoneta/wf_hot_standby.c
  src/libpgmoneta/wf_retention.c
Labels: feature
