Repository pgmoneta/pgmoneta, pull requests merged in 2025-03, with the labels that each got.

#506 Use GET_ENV macro for environment variable
  src/admin.c
Labels: bug

#509 Use startup packets to set server version
  AUTHORS
  doc/manual/97-acknowledgement.md
  doc/manual/advanced/97-acknowledgement.md
  src/include/security.h
  src/libpgmoneta/security.c
  src/libpgmoneta/server.c
Labels: enhancement

#518 [#517] Added pgmoneta_linux_version function to extract os kernel Ver…
  AUTHORS
  doc/manual/97-acknowledgement.md
  doc/manual/advanced/97-acknowledgement.md
  src/include/utils.h
  src/libpgmoneta/utils.c
  src/main.c
Labels: feature

#527 [#525] Splitted configuration into main, common and walinfo
  src/cli.c
  src/include/configuration.h
  src/include/pgmoneta.h
  src/libpgmoneta/aes.c
  src/libpgmoneta/archive.c
  src/libpgmoneta/backup.c
  src/libpgmoneta/bzip2_compression.c
  src/libpgmoneta/configuration.c
  src/libpgmoneta/gzip_compression.c
  src/libpgmoneta/info.c
  src/libpgmoneta/keep.c
  src/libpgmoneta/link.c
  src/libpgmoneta/logging.c
  src/libpgmoneta/management.c
  src/libpgmoneta/message.c
  src/libpgmoneta/network.c
  src/libpgmoneta/prometheus.c
  src/libpgmoneta/remote.c
  src/libpgmoneta/restore.c
  src/libpgmoneta/retention.c
  src/libpgmoneta/se_azure.c
  src/libpgmoneta/se_local.c
  src/libpgmoneta/se_s3.c
  src/libpgmoneta/se_ssh.c
  src/libpgmoneta/security.c
  src/libpgmoneta/server.c
  src/libpgmoneta/status.c
  src/libpgmoneta/utils.c
  src/libpgmoneta/verify.c
  src/libpgmoneta/wal.c
  src/libpgmoneta/walfile/wal_reader.c
  src/libpgmoneta/wf_archive.c
  src/libpgmoneta/wf_backup.c
  src/libpgmoneta/wf_bzip2.c
  src/libpgmoneta/wf_cleanup.c
  src/libpgmoneta/wf_delete.c
  src/libpgmoneta/wf_encryption.c
  src/libpgmoneta/wf_extra.c
  src/libpgmoneta/wf_gzip.c
  src/libpgmoneta/wf_hot_standby.c
  src/libpgmoneta/wf_link.c
  src/libpgmoneta/wf_lz4.c
  src/libpgmoneta/wf_manifest.c
  src/libpgmoneta/wf_permissions.c
  src/libpgmoneta/wf_restore.c
  src/libpgmoneta/wf_retention.c
  src/libpgmoneta/wf_sha256.c
  src/libpgmoneta/wf_verify.c
  src/libpgmoneta/wf_zstd.c
  src/libpgmoneta/workers.c
  src/libpgmoneta/workflow.c
  src/libpgmoneta/zstandard_compression.c
  src/main.c
  src/walinfo.c
Labels: feature

#528 [#525] Moved users, servers and admins to common config
  src/include/pgmoneta.h
  src/libpgmoneta/archive.c
  src/libpgmoneta/backup.c
  src/libpgmoneta/configuration.c
  src/libpgmoneta/info.c
  src/libpgmoneta/keep.c
  src/libpgmoneta/management.c
  src/libpgmoneta/network.c
  src/libpgmoneta/prometheus.c
  src/libpgmoneta/restore.c
  src/libpgmoneta/retention.c
  src/libpgmoneta/se_azure.c
  src/libpgmoneta/se_local.c
  src/libpgmoneta/se_s3.c
  src/libpgmoneta/se_ssh.c
  src/libpgmoneta/security.c
  src/libpgmoneta/server.c
  src/libpgmoneta/status.c
  src/libpgmoneta/utils.c
  src/libpgmoneta/verify.c
  src/libpgmoneta/wal.c
  src/libpgmoneta/walfile/wal_reader.c
  src/libpgmoneta/wf_archive.c
  src/libpgmoneta/wf_backup.c
  src/libpgmoneta/wf_bzip2.c
  src/libpgmoneta/wf_cleanup.c
  src/libpgmoneta/wf_delete.c
  src/libpgmoneta/wf_encryption.c
  src/libpgmoneta/wf_extra.c
  src/libpgmoneta/wf_gzip.c
  src/libpgmoneta/wf_hot_standby.c
  src/libpgmoneta/wf_link.c
  src/libpgmoneta/wf_lz4.c
  src/libpgmoneta/wf_manifest.c
  src/libpgmoneta/wf_permissions.c
  src/libpgmoneta/wf_restore.c
  src/libpgmoneta/wf_retention.c
  src/libpgmoneta/wf_sha256.c
  src/libpgmoneta/wf_verify.c
  src/libpgmoneta/wf_zstd.c
  src/libpgmoneta/workers.c
  src/libpgmoneta/workflow.c
  src/main.c
Labels: enhancement

#535 File-by-file incremental backup combine
  src/include/backup.h
  src/include/restore.h
  src/include/workflow.h
  src/include/workflow_funcs.h
  src/libpgmoneta/backup.c
  src/libpgmoneta/restore.c
  src/libpgmoneta/wf_restore.c
  src/libpgmoneta/workflow.c
Labels: enhancement

#540 [#533] Feat : Add docker support to pgmoneta
  AUTHORS
  contrib/docker/Dockerfile.alpine
  contrib/docker/Dockerfile.rocky9
  contrib/docker/pgmoneta.conf
  doc/GETTING_STARTED.md
  doc/manual/97-acknowledgement.md
  doc/manual/99-references.md
  doc/manual/advanced/12-docker.md
  doc/manual/advanced/97-acknowledgement.md
  doc/manual/user-15-docker.md
  doc/tutorial/17_docker.md
  pgmoneta.spec
Labels: feature

#505 feat: Enhance relpath error handling and validation
  src/include/walfile/relpath.h
  src/libpgmoneta/walfile/relpath.c
Labels: enhancement
