Repository pgmoneta/pgmoneta, pull requests merged in 2025-02, with the labels that each got.

#476 [#475] Make config argument optional and set default configuration path
  AUTHORS
  doc/manual/97-acknowledgement.md
  doc/manual/advanced/97-acknowledgement.md
  src/include/configuration.h
  src/walinfo.c
Labels: enhancement

#488 admin: support password through environment
  AUTHORS
  doc/GETTING_STARTED.md
  doc/man/pgmoneta-admin.1.rst
  doc/manual/97-acknowledgement.md
  doc/manual/advanced/03-installation.md
  doc/manual/advanced/97-acknowledgement.md
  doc/manual/user-01-quickstart.md
  doc/tutorial/01_install.md
  src/admin.c
Labels: feature

#489 Remove trailing spaces
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  cmake/FindLibcurl.cmake
  cmake/FindLibssh.cmake
  cmake/FindLz4.cmake
  cmake/FindPandoc.cmake
  cmake/FindPdflatex.cmake
  doc/Azure.md
  doc/CLI.md
  doc/DEVELOPERS.md
  doc/DISTRIBUTIONS.md
  doc/ENCRYPTION.md
  doc/GETTING_STARTED.md
  doc/S3.md
  doc/SSH.md
  doc/TEST.md
  doc/etc/pgmoneta.conf
  doc/man/pgmoneta-cli.1.rst
  doc/manual/02-installation.md
  doc/manual/98-licenses.md
  doc/manual/99-references.md
  doc/manual/advanced/05-backup.md
  doc/manual/advanced/07-keep.md
  doc/manual/advanced/08-restore.md
  doc/manual/advanced/98-licenses.md
  doc/manual/advanced/99-references.md
  doc/manual/dev-03-encryption.md
  doc/manual/dev-05-test.md
  doc/manual/dev-06-wal.md
  doc/manual/user-10-cli.md
  doc/tutorial/01_install.md
  doc/tutorial/04_backup_restore.md
  doc/tutorial/06_archive.md
  doc/tutorial/09_retention.md
  doc/tutorial/11_wal_shipping.md
  doc/tutorial/12_tls.md
  doc/tutorial/16_incremental_backup_restore.md
  doc/tutorial/16_local_test.md
  src/libpgmoneta/art.c
  test/CMakeLists.txt
  test/testsuite.sh
Labels: bug
