Repository pgmoneta/pgmoneta, pull requests merged in 2025-04, with the labels that each got.

#554 [#538] add --sort asc|desc option to list-backup command
  doc/manual/97-acknowledgement.md
  doc/manual/advanced/05-backup.md
  doc/manual/advanced/97-acknowledgement.md
  doc/manual/user-10-cli.md
  src/cli.c
  src/include/management.h
  src/include/utils.h
  src/libpgmoneta/backup.c
  src/libpgmoneta/management.c
Labels: feature

#521 [#514] Print line numbers in pgmoneta_backtrace
  AUTHORS
  doc/manual/97-acknowledgement.md
  doc/manual/advanced/97-acknowledgement.md
  src/include/utils.h
  src/libpgmoneta/utils.c
Labels: enhancement

#561 [#555] fix: macos compatibility
  .github/workflows/ci.yml
  CMakeLists.txt
  src/libpgmoneta/security.c
  src/libpgmoneta/utils.c
  test/testsuite.sh
Labels: enhancement

#508 [#415] Implemented the translation and filtering
  doc/CONFIGURATION.md
  doc/WALINFO.md
  doc/etc/pgmoneta_walinfo.conf
  doc/man/pgmoneta-walinfo.1.rst
  doc/manual/dev-06-wal.md
  doc/manual/user-02-configuration.md
  src/cli.c
  src/include/configuration.h
  src/include/pgmoneta.h
  src/include/utils.h
  src/include/wal.h
  src/include/walfile.h
  src/include/walfile/wal_reader.h
  src/libpgmoneta/configuration.c
  src/libpgmoneta/network.c
  src/libpgmoneta/prometheus.c
  src/libpgmoneta/utils.c
  src/libpgmoneta/wal.c
  src/libpgmoneta/walfile.c
  src/libpgmoneta/walfile/rm_btree.c
  src/libpgmoneta/walfile/rm_gist.c
  src/libpgmoneta/walfile/rm_heap.c
  src/libpgmoneta/walfile/rm_relmap.c
  src/libpgmoneta/walfile/rm_seq.c
  src/libpgmoneta/walfile/rm_standby.c
  src/libpgmoneta/walfile/rm_xlog.c
  src/libpgmoneta/walfile/wal_reader.c
  src/libpgmoneta/wf_link.c
  src/main.c
  src/walinfo.c
  test/tsclient.c
Labels: feature

#570 [#567] encrypt/compress/decrypt/decompress without config
  src/cli.c
Labels: bug

#572 [#566] Add freeBSD support in CI
  .github/workflows/ci.yml
  test/testsuite.sh
Labels: enhancement

#576 [#575] file logging: support environment variables
  AUTHORS
  doc/CONFIGURATION.md
  doc/manual/97-acknowledgement.md
  doc/manual/advanced/97-acknowledgement.md
  src/cli.c
  src/include/utils.h
  src/libpgmoneta/configuration.c
  src/libpgmoneta/logging.c
  src/libpgmoneta/utils.c
Labels: enhancement

#578 [#577] fix environment variables support
  src/libpgmoneta/configuration.c
  src/libpgmoneta/logging.c
Labels: enhancement

#580 [#542][#543] Rollup backup during deletion
  src/include/restore.h
  src/include/workflow.h
  src/include/workflow_funcs.h
  src/libpgmoneta/info.c
  src/libpgmoneta/restore.c
  src/libpgmoneta/utils.c
  src/libpgmoneta/wf_delete.c
  src/libpgmoneta/wf_link.c
  src/libpgmoneta/wf_restore.c
  src/libpgmoneta/workflow.c
Labels: enhancement

#590 [#524] Incremental backup restore size calculation
  src/include/backup.h
  src/include/info.h
  src/libpgmoneta/backup.c
  src/libpgmoneta/info.c
  src/libpgmoneta/restore.c
  src/libpgmoneta/wf_backup.c
Labels: enhancement

#604 [#600] Build: cmake 3.31+
  doc/CMakeLists.txt
Labels: enhancement

#597 [#550] API for pg_control
  src/include/security.h
  src/include/walfile/pg_control.h
  src/include/walfile/transaction.h
  src/libpgmoneta/pg_control.c
  src/libpgmoneta/security.c
  src/libpgmoneta/walfile/rm_xlog.c
Labels: feature

#613 [#612] Create backup.sha512 for entire backup
  doc/manual/advanced/05-backup.md
  src/include/security.h
  src/include/workflow_funcs.h
  src/libpgmoneta/backup.c
  src/libpgmoneta/keep.c
  src/libpgmoneta/wf_sha512.c
  src/libpgmoneta/workflow.c
Labels: feature

#602 [#595] Test suite: Use gcov and gcovr
  .github/workflows/ci.yml
  CMakeLists.txt
  doc/DEVELOPERS.md
  doc/TEST.md
  doc/WAL.md
  doc/manual/dev-06-test.md
  doc/manual/dev-07-codecoverage.md
  doc/manual/dev-08-wal.md
  src/CMakeLists.txt
  test/CMakeLists.txt
  test/Dockerfile.testsuite
  test/coverage.sh
  test/testsuite.sh
Labels: feature
